typography_spectrum: 0.7882695638108999
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.625
  lightness: 0.5525635534431785
  saturation: 0.6635843887925148
  rhythmicContrast: 0.3951787876430899
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9878
analytics:
  google: null
  facebook: null
  twitter: null
name: KeeneBehaviorSolutions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
